### ISSUE TITLE
Inflectional Forms Incorrect Generation on suffix and prefix

### ISSUE THREAD

**Issue by pineo** [cmput401-winter2019/cree-intelligent-dictionary#89]

**Comment by CoshUS** [comment]
Inflected Cree word forms with features that precede 
the lemma (in the analyses), e.g. with reduplication (RdplW+, RdplS+) or 
preverbs (anything with PV/...+) (or initial change: IC+), appear to 
only show the first feature and are not matched with the lemma.

**Comment by pineo** [comment]
Appears to be a backend issue - the "Context" that is passed, that for all other lemmas is the lemma to be displayed, for some reason, shows PV/... rather than the lemma.

**Comment by CoshUS** [comment]
Fixed in 7d8f94d6f8f9ae47f57cfc336ed437f7fddcbc68
However there is still a problem with "PV/apisîs" where FST_lookup returns (PV/apisîs, IPC, **Err/Orth**).
Most likely dictionary or fst problem.
